### ISSUE TITLE
Decal Orientation Wrong On Load

### ISSUE THREAD

**Issue by biscuitWizard** [PersistentSS13/PersistentOutreach13#43]
Make decals aligned correctly again after loading a save.

**Comment by PsyCommando** [comment]
Which decals have you seen that with?

Decals are annoying to save, because the object that represents them draws an overlay on the turf below and is destroyed on init. So depending on what kind of decal it was, there might be something different to do for each of them.
We used to save a copy of the object that applied the decal in a list for each turfs so they'd be re-drawn on load. But I don't think that was super efficient..

**Comment by biscuitWizard** [comment]
All decals. But especially floor_effects.

**Comment by biscuitWizard** [comment]
![image](https://user-images.githubusercontent.com/1904063/78087091-bfd48d00-7374-11ea-8b7e-cd159f2d262c.png)

**Comment by PsyCommando** [comment]
Are you saving the floor decal cache? That might be why its only drawing the default icon state for each floor decals. Its the list in code\game\turfs\flooring\flooring_decals.dm

**Comment by PsyCommando** [comment]
Not sure how it works exactly, but it seems like it wouldn't cooperate too much when saved..

**Comment by biscuitWizard** [comment]
No globals are saved. At all. Nor any subsystem states.

**Comment by PsyCommando** [comment]
Do you know how/if the /image type is handled then? It seems like that's what's stored in the decals and overlay list.

**Comment by biscuitWizard** [comment]
Have you checked saved_vars.json?

**Comment by PsyCommando** [comment]
Taking a look, thanks!

**Comment by PsyCommando** [comment]
Ok, so, after looking at the DB, it seems like the list that contains the overlays didn't serialize correctly possibly? Its not entirely related I think, but it might be something to look into in general.

The list_id for it has a corresponding list table entry, but nothing in the list_element table. And it says it has a non-zero length too.

**Comment by biscuitWizard** [comment]
length is not a useful column and should be ignored. I will likely drop that column at some point, it's not accurate. :)

**Comment by biscuitWizard** [comment]
![image](https://user-images.githubusercontent.com/1904063/78099148-de974b80-7395-11ea-83e8-e6b42945c657.png)

Overlays is something we're not allowed to serialize. Byond handles them or something. Or the AO system. They're auto-genned.

Decals is not however. And is the field you're actually looking for.

![image](https://user-images.githubusercontent.com/1904063/78099223-10101700-7396-11ea-80e9-a37eca9b1892.png)

![image](https://user-images.githubusercontent.com/1904063/78099243-1dc59c80-7396-11ea-830d-45a23f53bb15.png)

**Comment by PsyCommando** [comment]
Yeah, decals is the interesting one, but overlays is still specified in saved_vars.json. So I assumed you found a way to save those or something? I'll removed the references to underlays and overlays from saved_vars then.

One of the things I was trying is to deal with images differently, so instead of using "new" to create the image and set its variables, I'd use the "image()" proc. Since images are special and they're apparently virtual objects that applies a modifier on a loaded icon according to the byond reference.

**Comment by biscuitWizard** [comment]
This is fixed. If you'd like to see how this was solved, look at the above commit.
